# Dockerfile - postsec-docker
# 
# General purpose Dockerfile to setup Apache, PHP, MySQL
# environment for running the Post-Secondary Database Registration
# website.

FROM postsec/base

# copy over repo
COPY www/ /var/www/html